### ISSUE TITLE
Startup time and memory overhead of each isolate instance and polyglot context instance

### ISSUE THREAD

**Issue by shafqatevo** [davidfrickert/FunctionRunner#25]
Hi David,

Thanks for sharing this interesting work! I am exploring using isolates. I have couple questions:

1. What’s the typical startup time and memory overhead requirement for each isolate instance?

2. Have you tried launching polyglot contexts within isolates? If yes, what’s the startup time for a polyglot context within an isolate and what’s the additional memory overhead per such polyglot context instance?

Thanks!

**Comment by davidfrickert** [comment]
Hey @shafqatevo.

I don't currently use polyglot features of GraalVM, so I can't comment on that part.

For the Isolates, I can tell you that it depends on the concurrency levels of your application (in terms of startup time).
For concurrency=1 (single thread):
Isolate Startup Time (creation time): ~3-4ms
Isolate Destroy Time: ~1ms

Then as you increase concurrency, these times increase, but I currently don't have values for that.

In terms of memory, I think each Isolate on startup consumes around 1MB. But this I'm not sure, I need to collect more data.

**Comment by shafqatevo** [comment]
Thanks a lot @davidfrickert!

**Comment by shafqatevo** [comment]
Hi @davidfrickert, just a question - are those measurements for Graal Native or regular Graal?

**Comment by davidfrickert** [comment]
No worries, @shafqatevo!
Native, as far as I know, Isolates are only a feature of Native, you can't use them in regular Graal.

**Comment by shafqatevo** [comment]
@davidfrickert yes, that was a dumb question! I had forgotten that... :)

In a 2014 i5 iMac, we’re getting only around 150-250 microseconds to create an isolate. And 30 microseconds to tear down. That’s an order of magnitude less than your numbers. Hence had asked.

**Comment by davidfrickert** [comment]
@shafqatevo 
No worries!
Huh wow, impressive difference!

Are you perhaps using any configurations that aren't default in creating the isolates?

I'm running inside a vagrant virtualbox on a dual Xeon E5-2648L v4, maybe the virtualization is causing the difference here.
And also, my app is running inside docker.

Bare Metal -> Vagrant Virtualbox -> Docker

**Comment by shafqatevo** [comment]
Yes, I think your virtualization is causing the added latency. We're running directly on the 2014 i5 iMac machine with no special config.
