### ISSUE TITLE
Do you have an email/Discord? Similar interests

### ISSUE THREAD

**Issue by GavinRay97** [davidfrickert/FunctionRunner#31]
Hello, was checking out some of your code here and at your other repos (modified OpenWhisk Java runtime, and the master repo pulling in all the sub-repos).

We have similar interests I think, have been doing some work in this area as well, and maybe it could be nice to exchange ideas/thoughts if you're interested? 🙂 

If you don't want to publish your info, and you're interested in talking, mine is `ray(dot)gavin97(at)gm4i1(dot)com`

**Comment by davidfrickert** [comment]
Hey. I think I did reach out to you by e-mail but never got an answer.
You can hit me up on Koogas#5830 discord.
